//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlapoCC.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlapoCC.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prise.
        /// </summary>
        internal static string Prise {
            get {
                return ResourceManager.GetString("Prise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by number of bottles.
        /// </summary>
        internal static string SortByNumberOfBottles {
            get {
                return ResourceManager.GetString("SortByNumberOfBottles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by price.
        /// </summary>
        internal static string SortByPrice {
            get {
                return ResourceManager.GetString("SortByPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by price per bottle.
        /// </summary>
        internal static string SortByPricePerBottle {
            get {
                return ResourceManager.GetString("SortByPricePerBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by price per liter.
        /// </summary>
        internal static string SortByPricePerLiter {
            get {
                return ResourceManager.GetString("SortByPricePerLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product details.
        /// </summary>
        internal static string TitleProductDetails {
            get {
                return ResourceManager.GetString("TitleProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string TitleProducts {
            get {
                return ResourceManager.GetString("TitleProducts", resourceCulture);
            }
        }
    }
}
